name: ResourcepackSoundPlayer
main: goldbigdragon.github.io.main.Main
version: 1.2
api-version: 1.12
website: http://goldbigdragon.github.io/
author: GoldBigDragon
description: Resourcepack sound player!
commands:
  rsp:
    #usage: /rsp
    description: §fSee ResourcepackSoundPlayer's information. §e/rsp